# Generated by Django 4.2 on 2023-05-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carburant',
            fields=[
                ('idcarburant', models.AutoField(db_column='idCarburant', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'carburant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('idmarque', models.AutoField(db_column='idMarque', primary_key=True, serialize=False)),
                ('logo', models.IntegerField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'marque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('date_arr', models.DateField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'transmission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('mdp', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('idcar', models.AutoField(db_column='idCar', primary_key=True, serialize=False)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('doors', models.IntegerField(blank=True, null=True)),
                ('power', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voiture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('iduser', models.OneToOneField(db_column='idUser', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='django_app.utilisateur')),
                ('adresse', models.CharField(max_length=254)),
                ('cin', models.CharField(max_length=50)),
                ('photo', models.TextField(blank=True, null=True)),
                ('liste_noire', models.IntegerField(blank=True, null=True)),
                ('permis', models.CharField(blank=True, max_length=20, null=True)),
                ('passport', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('observation', models.CharField(blank=True, max_length=254, null=True)),
                ('societe', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('date_permis', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuperUtilisateur',
            fields=[
                ('iduser', models.OneToOneField(db_column='idUser', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='django_app.utilisateur')),
                ('admin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'super_utilisateur',
                'managed': False,
            },
        ),
    ]
